plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\docunents\\my work\\My_Portfolio\\dist\\client"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/*"

[headers.values]
cache-control = "public, max-age=31536000, immutable"